config/routes.rb
Rails.application.routes.draw do
  get 'instructors/index'
  get 'courses/index'
  get 'students/index'
  get 'cohorts/index'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'sessions/new'
  root to: "pages#launch_center"
  get '/student_portal', to: 'pages#student_portal'
  get '/instructor_portal', to: 'pages#instructor_portal'
  get '/course_portal', to: 'pages#course_portal'
  get '/cohort_portal', to: 'pages#cohort_portal'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :students
resources :cohorts
resources :courses
resources :instructors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
    has_and_belongs_to_many :instructors
    has_and_belongs_to_many :students
    
    has_and_belongs_to_many :courses
end

app/models/course.rb
class Course < ApplicationRecord 
    has_and_belongs_to_many :cohorts
    
    
end

app/models/instructor.rb
class Instructor < ApplicationRecord
    has_and_belongs_to_many :cohorts

    validates :salary, presence:true, numericality: { only_integer: true, greater_than: 0 }

end
 #repference singular table 

app/models/student.rb
class Student < ApplicationRecord
    
    has_and_belongs_to_many :cohorts

end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  def index
  end
  def destroy
    @rmv_cohort = Cohort.find(params[:cohort_id]).destroy
   
  end
  def update
    @updt_cohort = Cohort.find(params[:cohort_id]).update
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
  end
  def destroy
    @rmv_course = Course.find(params[:course_id]).destroy
   
  end
  def update
    @updt_course = Course.find(params[:course_id]).update
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  def index
  end

  def destroy
    @rmv_instructor = Instructor.find(params[:instructor_id]).destroy
   
  end
  def update
    @updt_instructor = Instructor.find(params[:instructor_id]).update
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def launch_center
    def create 
        User.create(username:params[:user_name], email:params[:email], password:params[:password])
    end
  end
  def student_portal
    @all_students=Student.all
    
    
  end
  def instructor_portal
    @all_instructors=Instructor.all
    
  end
  def course_portal
    @all_courses=Course.all

    def destroy
      if current_user
        @course= Cohort.find(params[:id])
      end
      redirect_to '/pages'
    end
  end
  def cohort_portal
    @all_cohorts=Cohort.all
    
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
  end
  def destroy
    @rmv_student = Student.find(params[:student_id]).destroy
   
  end
  def update
    @updt_student= Instructor.find(params[:student_id]).update
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
    
    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cohorts/index.html.erb
<h1>Cohorts#index</h1>
<p>Find me in app/views/cohorts/index.html.erb</p>

app/views/courses/index.html.erb
<h1>Courses#index</h1>
<p>Find me in app/views/courses/index.html.erb</p>

app/views/instructors/index.html.erb
<h1>Instructors#index</h1>
<p>Find me in app/views/instructors/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css"/>
  <link rel="stylesheet" href="https://unpkg.com/picnic">
</head>
<body>
  <div id="header">
    <% if signed_in? -%>
      <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
    <% else -%>
      <%= link_to t(".sign_in"), sign_in_path %>
    <% end -%>
  </div>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

  <%= yield %>
</body>
</html>

app/views/pages/cohort_portal.html.erb
<h1> Cohort Portal</h1>
<div>
  <%= form_tag("/cohort/create", method: "post") do %>
    <%= text_field(:cohort, :name, placeholder: "Cohort Name") %>
    <%= text_field(:cohort, :start_date, placeholder: "Start Date") %>
    <%= text_field(:cohort, :end_date, placeholder: "End Date") %>
    <button class="ui primary button">Save</button>
  <% end %>
</div>
<br>
<br>
<div class="full half-500 third-800">
  <table class="primary tab">
    <thead>
      <tr>
        
        <th>Cohort Name</th>
        <th> Start Date</th>
        <th> End Date</th>
        <th><button class="ui primary button">
        Save
      </button> </th>
        <th> </th>
      </tr>
    </thead>
    <tbody>
      <% @all_cohorts.each do |cohorts| %>
      <tr>
        <td><%= cohorts.name %></td>
        <td><%= cohorts.start_date %></td>
        <td><%= cohorts.end_date %></td>
        <td><button class='success'>Success</button></td>
        <td><%= link _to 'Rmv_Cohort'button class='error'>Success</button></td>
        </tr>
        <button class="ui secondary button">
        Okay
      </button>
      <button class="ui button">
        Cancel
      </button>
    <% end %>
    </tbody>
  </table>
</div>


<button class="ui primary button">
  Save
</button>
<button class="ui button">
  Discard
</button>

app/views/pages/course_portal.html.erb
<h1> Course Portal</h1>
<div>
  <%= form_tag("/course/create", method: "post") do %>
    <%= text_field(:course, :name, placeholder: "Course Name") %>
    <%= text_field(:course, :total_hours, placeholder: "Total Hours") %>
    <%= text_field(:course, :start_date, placeholder: "Start Date") %>
    <%= text_field(:course, :end_date, placeholder: "End Date") %>
    <button class="ui primary button">Save</button>
  <% end %>
</div>
<br>
<br>
<div class="tab">
  <table class="primary">
    <thead>
      <tr>
        
        <th>Course Name</th>
        <th> Total Hours</th>
        <th> </th>
        <th> </th>
      </tr>
    </thead>
    <tbody>
      <% @all_courses.each do |courses| %>
      <tr>
        <td><%= courses.name %></td>
        <td><%= courses.total_hours %></td>
        <td><button class='success'>Success</button></td>
        <td><button class='error'>Success</button></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/pages/instructor_portal.html.erb
<h1> Instructor Portal</h1>
<div>
  <%= form_tag("/instructor/create", method: "post") do %>
    <%= text_field(:instructor, :first_name, placeholder: "First Name") %>
    <%= text_field(:instructor, :last_name, placeholder: "Last Name") %>
    <%= text_field(:instructor, :age, placeholder: "age") %>
    <button class="ui primary button">Save</button>
  <% end %>
</div>
<br>
<div>
  <table class="primary">
    <thead>
      <tr>
        
        <th>First Name</th>
        <th> Last Name</th>
        <th>Age</th>
        <th>Education</th>
        <th>Salary</th>
        <th class="edit"></th>
        <th class="edit"></th>
      </tr>
    </thead>
    <tbody>
      <% @all_instructors.each do |instructors| %>
      <tr>
        <td><%= instructors.first_name %></td>
        <td><%= instructors.last_name %></td>
        <td><%= instructors.age %></td>
        <td><%= instructors.highest_education_completed %></td>
        <td><%= instructors.salary %></td>
        <td><%= link_to 'button class="ui primary button">Edit</button></td>
        <td><button class="ui secondary button">Delete</button></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/pages/launch_center.html.erb
<h1>Launcher</h1>
<% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= button_to 'Sign out', sign_out_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>
    <% end %>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>
<p>Launcher </p>

app/views/pages/student_portal.html.erb
<h1> Student Portal</h1>
<div>
  <%= form_tag("/student/create", method: "post") do %>
    <%= text_field(:student, :first_name, placeholder: "First Name") %>
    <%= text_field(:student, :last_name, placeholder: "Last Name") %>
    <%= text_field(:student, :age, placeholder: "age") %>
    <button class="ui primary button">Save</button>
  <% end %>
</div>
<br>
<div>
  <table class="primary">
    <thead>
      <tr>
        
        <th>First Name</th>
        <th> Last Name</th>
        <th>Age</th>
      </tr>
    </thead>
    <tbody>
      <% @all_students.each do |students| %>
      <tr>
        <td><%= students.first_name %></td>
        <td><%= students.last_name %></td>
        <td><%= students.age %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/students/index.html.erb
<h1>Students#index</h1>
<p>Find me in app/views/students/index.html.erb</p>

app/views/users/_form.html.erb
<div class="text-field">
 <form.lable :username>
 <form.text_field :username, type: 'username'> 

<%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>